# Uncomment the next line to define a global platform for your project
platform :ios, '12.3'

source 'https://github.com/pokanop/cocoapods-pokanop.git'

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo
  pod 'Boing'

end
